11/19修正分 高田
raveger/Todo-list pull request #8
Opened 2020-11-19 08:45 UTC by raveger

ご指摘いただいた箇所を修正しました。

また、一部の修正内容については以下の通りに行っております。
①encode.js内のオブジェクト名をobj⇒todoとすると、4行目のtodoと名称が被ってしまうため、obj⇒todosとしました。

②model.goの構造体ですが、TodoData構造体のみとしたとき、一覧取得が出来なくなりました。
(todolistテーブルでidをint型として作成しているからだと思われます。)
なので、一覧取得機能用にListup構造体を残しています。

2020-11-20 07:53 UTC, garireo2549 requested changes

2020-11-20 07:53 UTC, garireo2549 commented on ToDo/conversion.js
> +                console.log(id);
必要ないんで消しましょか

2020-11-20 07:53 UTC, garireo2549 commented on ToDo/encode.js
> +    const todos = {
被るのみてなかった、申し訳ない
じゃあ名前は`createTodo`にしますか

2020-11-20 07:53 UTC, garireo2549 commented on ToDo/main.go
> +func updateTODO(w http.ResponseWriter, r *http.Request) {
これもエラーはmainで処理しましょう

2020-11-20 07:53 UTC, garireo2549 commented on ToDo/main.go
> -		log.Println(err)
必要です
ハンドラーはエラーを標準出力に表示させましょう

2020-11-20 07:53 UTC, garireo2549 commented on ToDo/main.go
> -		log.Println(err)
必要です
ハンドラーはエラーを標準出力に表示させましょう

2020-11-20 07:53 UTC, garireo2549 commented on ToDo/main.go
> -		log.Println(err)
必要です
ハンドラーはエラーを標準出力に表示させましょう

2020-11-20 07:53 UTC, garireo2549 commented on ToDo/main.go
> -		log.Println(err)
必要です
ハンドラーはエラーを標準出力に表示させましょう

2020-11-24 00:30 UTC, garireo2549 approved these changes

2020-11-24 05:48 UTC, skanehira commented on ToDo/api/delete.go
> +	_, err := DB.Exec("DELETE FROM todolist WHERE id=?", id)
細かいけど、 WHERE id = ? って感じでスペースを空けておこう
そのほうが読みやすい

2020-11-24 05:48 UTC, skanehira commented on ToDo/api/ins.go
>  //INSERT処理を行う関数
Goではコメントは // の後はスペースを空ける
```go
// comnent
```

2020-11-24 05:48 UTC, skanehira commented on ToDo/encode.js
> +    const todo = document.getElementById("valueTodo").value;
空の場合の入力チェックは必要だね

2020-11-24 05:48 UTC, skanehira commented on ToDo/model/model.go
> +type TodoData struct {
1.  todo は略語なので TODO が良いね
2. TODOだけで十分意味が通じるので、 Data は不要だね

2020-11-24 09:23 UTC, skanehira requested changes

2020-11-24 09:23 UTC, skanehira commented on ToDo/api/delete.go
> +	_, err := DB.Exec("DELETE FROM todolist WHERE id= ?", id)
WHERE id = ? だね

2020-11-24 11:00 UTC, keijiokamoto approved these changes

2020-11-25 00:14 UTC, raveger commented on ToDo/api/delete.go
> +	_, err := DB.Exec("DELETE FROM todolist WHERE id= ?", id)
idの後のスペースを見落としていました申し訳ありません。修正しましたので、ご確認よろしくお願い致します。

2020-11-25 02:20 UTC, skanehira approved these changes

2020-11-27 06:42 UTC, skanehira requested changes

2020-11-27 06:42 UTC, skanehira commented on ToDo/conversion.js
> +        async doRemove(item) {
item -> todo

2020-11-27 06:42 UTC, skanehira commented on ToDo/display/display.html
> +                    <tr v-for="item in list" v-bind:key="item.id">
todo in todos

2020-11-27 06:42 UTC, skanehira commented on ToDo/conversion.js
> +        list: [],
listだと「なんのリスト」なのか分かりづらいので todos にしよう

2020-11-27 06:42 UTC, skanehira commented on ToDo/update/update.js
> +var app = new Vue({
更新もまとめて1つの画面にしようか

2020-11-27 08:10 UTC, skanehira requested changes

2020-11-27 08:10 UTC, skanehira commented on ToDo/index.js
> +        async doAdd() {
async/awaitは必要ないね
これは非同期処理を順次に処理していきたいときに使う
今はthenの中に次の処理書いているから、レスポンスが返ってくればthenが呼ばれるのにで、順次に処理できている

2020-11-27 08:10 UTC, skanehira commented on ToDo/index.js
> +        update: {},
動詞だけだと「なにを」ってなるので、
createTodoForm
updateTodoForm
にするとわかりやすくなる

2020-11-27 08:27 UTC, skanehira approved these changes

2020-11-27 08:29 UTC, merged